alias ..='cd ..'
alias ...='cd ../..'
alias l='ls -la'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias vd='nvim -d'

alias st='git status'
alias di='git diff'
alias ad='git add'
alias ci='git commit'
alias co='git checkout'
alias pu='git push'
alias up='git pull --ff-only'
alias br='git branch'
alias fe='git fetch'
alias lo='git log --oneline --decorate --graph'
