import path from 'node:path';

function pluginContent(specs) {
  return `// GENERATED by scripts/install-agent-hooks from ai/hooks/**/*. Do not edit by hand.
import { spawn } from "node:child_process";

const HOOKS = ${JSON.stringify(specs.map((spec) => ({
    id: spec.id,
    handlerPath: spec.handlerPath,
    matcher: spec.matcher,
  })), null, 2)};

function runHook(hook, command, cwd) {
  return new Promise((resolve, reject) => {
    const child = spawn("python3", [
      hook.handlerPath,
      "--client",
      "opencode",
      "--format",
      "decision",
      "--hook-id",
      hook.id,
    ], { stdio: ["pipe", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk) => { stdout += chunk; });
    child.stderr.on("data", (chunk) => { stderr += chunk; });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code !== 0) {
        reject(new Error(stderr.trim() || \`Hook \${hook.id} failed with exit code \${code}\`));
        return;
      }
      try {
        resolve(JSON.parse(stdout || "{}"));
      } catch (error) {
        reject(new Error(\`Hook \${hook.id} returned invalid JSON: \${error.message}\`));
      }
    });
    child.stdin.end(JSON.stringify({ command, cwd }));
  });
}

async function checkCommand(command, cwd) {
  if (!command) return;
  for (const hook of HOOKS) {
    const result = await runHook(hook, command, cwd);
    if (result.decision === "deny") {
      throw new Error(result.reason || \`Blocked by \${hook.id}\`);
    }
  }
}

export const DotfilesAgentHooks = async () => ({
  "tool.execute.before": async (_input, output) => {
    const cwd = output?.args?.cwd ?? output?.args?.workingDirectory ?? process.cwd();
    await checkCommand(output?.args?.command ?? output?.args?.cmd, cwd);
  },
  "command.execute.before": async (input) => {
    const command = [input.command, input.arguments].filter(Boolean).join(" ");
    const cwd = input.cwd ?? input.workingDirectory ?? process.cwd();
    await checkCommand(command, cwd);
  },
});
`;
}

export function render(specs, context) {
  const targetPath = path.join(context.home, '.config/opencode/plugins/dotfiles-search-guard.js');
  return [{ targetPath, content: pluginContent(specs) }];
}
